### ISSUE TITLE
Crash on module load

### ISSUE THREAD

**Issue by cschol** [danieldavies99/DanielDaviesVCV#4]
Crash on Ubuntu 20.04, Rack 2.0.2

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fc6f339a859 in __GI_abort () at abort.c:79
#2  0x0000000000403dc5 in  ()
#3  0x00007fc6f33bb210 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007fc6f00261d4 in DigitDisplay::draw(rack::widget::Widget::DrawArgs const&) () at /home/cschol/src/Rack-2.0-Home/plugins/SequelSequencers/plugin.so
#5  0x00007fc6f3abcca1 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () at ./libRack.so
#6  0x00007fc6f3abcdca in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#7  0x00007fc6f3a80e11 in rack::app::ModuleWidget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#8  0x00007fc6f3abcca1 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () at ./libRack.so
#9  0x00007fc6f3abcdca in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#10 0x00007fc6f3abcca1 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () at ./libRack.so
#11 0x00007fc6f3abcdca in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#12 0x00007fc6f3aa163b in rack::app::RackWidget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#13 0x00007fc6f3abcca1 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () at ./libRack.so
#14 0x00007fc6f3abcdca in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#15 0x00007fc6f3aba4c9 in rack::widget::ZoomWidget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#16 0x00007fc6f3abcca1 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () at ./libRack.so
#17 0x00007fc6f3abcdca in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#18 0x00007fc6f3abcca1 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () at ./libRack.so
#19 0x00007fc6f3abcdca in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#20 0x00007fc6f3a33dc3 in rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#21 0x00007fc6f3abcca1 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () at ./libRack.so
#22 0x00007fc6f3abcdca in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () at ./libRack.so
#23 0x00007fc6f3a5c3a8 in rack::window::Window::step() () at ./libRack.so
#24 0x00007fc6f3a5c5f8 in rack::window::Window::run() () at ./libRack.so
#25 0x000000000040386d in main ()
```

**Comment by danieldavies99** [comment]
This should be fixed by https://github.com/danieldavies99/sequel/pull/5 which is now merged into master.
